language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# Tests
script:
  - cd /home/travis/build/TEComputerIEEE/IEEE-TEC-Bot/ieee_tec_bot &&  python3 -m pytest
notifications:
  email:
    on_success: never
    on_failure: always